name: Publish Project to all Maven repositories

on:
  push:
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Write Gradle build properties to `~/.gradle/gradle.properties`
        run: |
          mkdir -p ~/.gradle
          printf "org.gradle.jvmargs=-Xmx3G -XX:+UseParallelGC\n" >> ~/.gradle/gradle.properties
          printf "org.gradle.vfs.watch=false\n" >> ~/.gradle/gradle.properties
          printf "org.gradle.parallel=false\n" >> ~/.gradle/gradle.properties
        shell: bash

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version-file: .java-version

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew publishAllPublicationsToGithubRepository

      - run: ./gradlew publishAllPublicationsToMavenCentralRepository

      - run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.gradle_publish_key }} -Pgradle.publish.secret=${{ secrets.gradle_publish_secret }}
